[package]
name = "javawrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
quit = "2.0"
serde = { version = "1.0", features = ["derive"] }
confy = "0.3"

#msgbox = "0.7"

[build-dependencies]
embed-resource = "2.1"

[profile.release]
lto = true
strip = true